### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1059]
When every module is updated to be color scheme-able using custom properties (see #1058) we will be able to offer a dark mode in skin. We also need a colour map from design team.

Because this will take a lot of work, I propose we phase this in using an experimental, opt in class, `body.skin-experiment-1`, this will allow us to play around with dark mode in the interim and convert a few modules at a time.

Articles:

* https://stackoverflow.blog/2020/03/31/building-dark-mode-on-stack-overflow

![s-l1000](https://user-images.githubusercontent.com/38065/77379777-c50f5780-6d36-11ea-9ccf-f9ce82710db6.jpg)

**Comment by Dorson** [comment]
Great idea for testing if you already had all the CSS colors inside of variables :+1: 

Recently, I coded the Dark Mode switch in CSS and basic Java Script.

did use `:root.default-color-class` as the default rule to overwrite all the other possible color classes that the user can set in `html.color-class, or the body.color-class. ` Helps to overwrite the automatic dark mode of the browser, if the user wants to have it custom in the moment. 

In my version of the dark mode switch we can have multiple color themes in one CSS file and call or remember them with a short JS function.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

I did my own custom JS code, instead of libraries.

In case, you want to use the jQuery then just use toggleClass( className ) for the  CSS color class on the html tag. Define the colors in CSS variable groups. Then remember to set the color theme class on every page-load from the stored setting in the localStorage.

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:

**Comment by ianmcburnie** [comment]
Thanks @Dorson. I'll take a look at your link when I next get a chance.

**Comment by ianmcburnie** [comment]
The vast majority of work is now done in 5.6.0 branch, so closing this ticket. Dark mode will remain behind a flag until v11 however.

We have one more ticket that is scoped at one last sweep through every component with the new update from design team: #1157
