### ISSUE TITLE
Color diff between select & combobox in DS4

### ISSUE THREAD

**Issue by malughanshyam** [eBay/skin#1212]
# Bug Report

## Description

My page is on DS4 and it has both "Select" as well as "Combobox"
There is inconsistency in colors of both in ebay skin 

My page: 
![image](https://user-images.githubusercontent.com/5460329/89856730-f5715a00-db4e-11ea-8c53-a914f4a843a1.png)
The Campaign dropdown is "ebayui/ebay-combobox" and the Metric dropdown is "ebayui/ebay-select". 
Look at the color difference. 

Campaign dropdown (ebay-combobox)  has 
```color: var(--combobox-foreground-color,#333);```

Metric dropdown (ebay-select) has 
```var(--select-foreground-color,#555);```

### Why are they differentiated so visibly in DS4 while they are **EXACTLY** the same in DS6? 

-----

### DS6

**Select**
![image](https://user-images.githubusercontent.com/5460329/89856628-a0354880-db4e-11ea-81ba-9f0b33a351d5.png)

https://github.com/eBay/skin/blob/master/dist/select/ds6/select.css#L17
```
color: var(--select-foreground-color,#111820);
```

**Combobox**

![image](https://user-images.githubusercontent.com/5460329/89856440-21d8a680-db4e-11ea-9788-f9e5e23469af.png)

https://github.com/eBay/skin/blob/master/dist/combobox/ds6/combobox.css#L159
```
color: var(--combobox-foreground-color,#111820);
```

--------

### DS4

**Select**

![image](https://user-images.githubusercontent.com/5460329/89856267-a8d94f00-db4d-11ea-993c-ff6e39c94a41.png)

https://github.com/eBay/skin/blob/master/dist/select/ds4/select.css#L10
```
color: var(--select-foreground-color,#555);
```

**Combobox**

![image](https://user-images.githubusercontent.com/5460329/89856383-fb1a7000-db4d-11ea-8541-7732c26096ba.png)

https://github.com/eBay/skin/blob/master/dist/combobox/ds4/combobox.css#L147
```
color: var(--combobox-foreground-color,#333);
```

**Comment by ianmcburnie** [comment]
Long answer: The DS4 system is legacy (circa 2013). For sometime now we have been in the process of migrating DS4 onto the DS6.5/One Experience system (i.e. color palette, typography, icongraphy, token aliases, etc). Way back, when DS4 first started, the different types of drop downs were all different colours, therefore it is inevitable that one or two fit & finish bugs have surfaced as we attempt to normalize that old system onto the new design token system. The good news is we are almost there...

Short answer: this will most likely be fixed in v11 as we move one step closer to getting DS4 and DS6 onto the same system of design token aliases.

**Comment by malughanshyam** [comment]
Makes sense. Can you please add the fix in 10.x as obviously v11 is a major version change ==> breaking change.
