### ISSUE TITLE
Select: alignment issue

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1253]
Test case can be found under global/stories

![Screen Shot 2020-09-21 at 10 53 40 AM](https://user-images.githubusercontent.com/38065/93803418-ad3b6200-fbf9-11ea-9707-afba28079239.png)

**Comment by agliga** [comment]
The issue seems to be the `font-size` is too large for the height given. 
For ds6 it's currently `font-size-18`. Setting it to `font-size-16` works, however this is using a global large font size. 
What's weird is for ds4 the default large font size is `font-size-16` while the ds6 one is `font-size-18`. Is this how it is supposed to be @ianmcburnie or is it a typo.

**Comment by ianmcburnie** [comment]
Yes, DS4 and DS6 are 16 and 18 respectively. I did think about normalizing them both to the same value in v11. If you think it's going to help, then maybe we should...

**Comment by ianmcburnie** [comment]
Done.
