### ISSUE TITLE
LightboxDialog: ugly in mini mode when not enough content

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#1380]
When less than two lines of content you get this:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/2737310/110632940-7c031e00-81a8-11eb-808d-f5a167bd3421.png">

Possible solutions:
- reposition the button
- change `min-height` of `.lightbox-dialog__window--mini` from 55px to 70px

**Comment by edvardsniedre** [comment]
Please see this additional things I spotted. Tested on v12.2.0.

- does not fit on devices under 400px due to max-width.  Screenshot on Samsung Galaxy 21s. Was closed in #1301 but issue seems to be still present.
<img width="335" alt="Screenshot 2021-03-22 at 22 05 48" src="https://user-images.githubusercontent.com/7050068/112064391-c8603d80-8b5a-11eb-87c1-50c109f6f441.png">

![Large GIF (774x904)](https://user-images.githubusercontent.com/7050068/112067986-e761ce00-8b60-11eb-80e6-3a25c0f11816.gif)


- close button outline in iOS Safari collapses (related to negative outline-offset).
<img width="878" alt="Screenshot 2021-03-22 at 21 14 29" src="https://user-images.githubusercontent.com/7050068/112064487-f180ce00-8b5a-11eb-99a0-db25f34a026c.png">


![Large GIF (554x622)](https://user-images.githubusercontent.com/7050068/112067958-dca73900-8b60-11eb-8c96-237d8be435df.gif)

**Comment by ianmcburnie** [comment]
Min-height issue fixed in 12.3.0 (other issues tracked separately).
