### ISSUE TITLE
Radio buttons: labels with larger font are misaligned

### ISSUE THREAD

**Issue by darkwebdev** [eBay/skin#1399]
Radio buttons look fine when using small font (16px), but this is what it looks like with larger font sizes (middle - 18px, right - 20px):
<img width="332" alt="image" src="https://user-images.githubusercontent.com/2737310/113897057-d05ee500-97ca-11eb-8067-82a9b0b77d16.png">

Labels move up. It would be really cool if the labels were vertically aligned with the icons.

Possible solutions:
1.
```
.radio {
  align-items: center;
}
span.field {
  display: inline-flex;
}
```
<img width="135" alt="image" src="https://user-images.githubusercontent.com/2737310/113900393-0ea9d380-97ce-11eb-8e7c-03453fa23a52.png">

2.
```
.radio {
  align-items: center;
  height: 1.4em;
}
```
<img width="343" alt="image" src="https://user-images.githubusercontent.com/2737310/113903346-2c2c6c80-97d1-11eb-89c0-363f4a1d8d15.png">

**Comment by ianmcburnie** [comment]
I think the original idea was to use the field module to assist with alignment, due to certain cross browser weirdness. Having said that, now that a certain browser is out of the picture, it might be easier for us to do this with relying on field (field was created a LONG time ago). Will investigate. Thanks!

**Comment by ianmcburnie** [comment]
Closing as we have a "workaround", but the field module probably needs a revisit in v13.
