### ISSUE TITLE
Add social icons to icon library

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1603]
As teams push for more social media service integration, the use of the official brand logos is increasing. To account for this usage across teams, we've opted to provide these assets in the main library for easier reference and to avoid teams using outdated brand icons.

These are only available in white (#FFF) and black (#000).
[icons_social.zip](https://github.com/eBay/skin/files/7585249/icons_social.zip)

**Comment by mumagnusson** [comment]
@ianmcburnie and @agliga the Stores PM team were wondering what the timeline would be on this. They are looking to complete their new social widget before Christmas so they can start integrating with different domain teams in January. Thanks!

**Comment by ianmcburnie** [comment]
@mumagnusson It should be something we can squeeze in, but I'm hesitant to guarantee it. Rather than a team be blocked by us on icons, I would recommend they just include them locally in their project until they become available in Skin. It would be an easy task to switchover when they are ready. I will try and find a slot for this on our roadmap soon.

**Comment by mumagnusson** [comment]
Thanks @ianmcburnie! I will let the team know that there is that option.
