### ISSUE TITLE
Update all star icons

### ISSUE THREAD

**Issue by rbascue** [eBay/skin#1817]
We've updated the empty and half star icons to improve contrast in reviews and ratings.

[Component to update →](https://opensource.ebay.com/ebayui-core/?path=/story/graphics-icons-ebay-star-rating--dynamic-stars)

[Figma source →](https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/eBay-Design-System?node-id=66513%3A95860)

### Star icon assets
[updated_star_assets_202207221405.zip](https://github.com/eBay/skin/files/9172158/updated_star_assets_202207221405.zip)

### In-context example
![image](https://user-images.githubusercontent.com/35155833/180568889-013aa346-9383-4cd3-8fc2-c5bf20a120b1.png)

**Comment by ratinsl** [comment]
Hi All,
We have slightly updated the star assets since this ticket was created. I've been talking with Arthur about the assets he needs and wanted to supply a new zip folder that contains the 3 new individual star assets (empty, half, filled) across two sizes as well as the legacy 5-star assets (11 in total) also across two sizes.

Please note that we currently only use the 16px size, but providing 24px size if needed. Arthur mentioned that you can try to target the fill and stroke colors now across browsers, so we are supplying these icons with active strokes, meaning they are not flattened/outlined like we normally do. If there are any issues with this, we can re-supply flattened icons. The 5-star asset names match skin, but you will most likely need to rename the individual star assets.

Please reach out on slack if you have any questions,
Ryan Tinsley

[220908_Review_Star_Updates.zip](https://github.com/eBay/skin/files/9531662/220908_Review_Star_Updates.zip)
<img width="1030" alt="220908_Review_Star_Upates_Color_Ref" src="https://user-images.githubusercontent.com/33495986/189255245-98ab9c1f-0dae-445f-8d48-6ccc7793215b.png">
