### ISSUE TITLE
Section notice - Action and dismiss properties and rules

### ISSUE THREAD

**Issue by randybascue** [eBay/skin#1883]
The section-notice is styled similarly to the page-notice with properties to show an action and a dismiss "X". The dismiss X is always aligned top-right. The action can be inline to the right or below the body content depending on the width of the notice and the amount of content.

![image](https://user-images.githubusercontent.com/35155833/192607671-ea082aca-9ae5-4a62-9031-7cf81bed126b.png)

**Comment by rbascue** [comment]
[Playbook](https://playbook.corp.ebay.com/PlaybookApp#/product-guidelines/patterns/section-notice)

**Comment by ArtBlue** [comment]
@randybascue , it looks like Playbook has some of the specs for the Section Notice (wider) vertically centered. Since we recently made the switch for Page Notice to be top aligned for all scenarios (and this pattern is following that), I'm going to assume those portions of the Section Notice specs are outdated. I'm going to implement the changes for Section Notice to be consistent with Page Notice.

**Comment by randybascue** [comment]
Correct. I've submitted a ticket to DT to get those updated
