### ISSUE TITLE
ebay-progress-stepper wrap issue for long words

### ISSUE THREAD

**Issue by jfan04** [eBay/skin#1982]
ebay-progress-stepper wrap issue for long words, like in DE language
![Screen Shot 2023-02-09 at 2 50 49 PM](https://user-images.githubusercontent.com/10121299/217956984-9da1db39-b4d7-4fbd-a0f6-c75fee0813e4.png)

**Comment by agliga** [comment]
This is an invalid bug. This is not happening locally and the words seem just fine. The container is expanding properly. There is overflow and a scrollbar, but this is expected at this screen size
<img width="360" alt="Screen Shot 2023-02-10 at 10 15 20 AM" src="https://user-images.githubusercontent.com/1755269/218166392-18e5b4a9-f283-4af4-8832-2899def66296.png">
My guess is this is due to an override on the app side. 
For now, I added a story for small screens so we can make sure this does not break in the future.
