### ISSUE TITLE
ebay-textbox: multi-line scrollbar incorrectly rendered

### ISSUE THREAD

**Issue by maxrchung** [eBay/skin#2200]
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

The vertical scrollbar for multi-line textbox does not look rendered correctly in Chrome. The top-right and bottom-right corners appear cut off by the scrollbar and do not have the rounded border.

See demo video below for more context.

### Expected behavior

The top-right and bottom-right corners should be rounded corners with the correct border color.

### Skin version

16.8.0

### Device/OS/Browser info

<img width="303" alt="image" src="https://github.com/eBay/skin/assets/3955187/89daf0f6-a675-46c0-862e-92d1eacc81d6"> 

<img width="706" alt="image" src="https://github.com/eBay/skin/assets/3955187/97ab5b8d-3e12-4e9d-997f-915ff704475b">

### Steps to reproduce

```bash
1. Configure your OS to make scrollbars always visible.
2. This is reproducible on the Skin documentation page. Go to https://opensource.ebay.com/skin/#textbox
3. Scroll down to "Multi-line Textbox" section.
4. Enter in very long text so that the vertical scrollbar appears.
5. Click outside of the textbox to lose focus.
6. Verify that the corners of the textbox look incorrectly rendered.
```

### Additional context

Demo video:

https://github.com/eBay/skin/assets/3955187/8b33ec3e-1189-4b69-88c8-db9993e27f02

**Comment by agliga** [comment]
This one is actually a browser issue not our issue. 
The top left is the only thing we can possible fix, but that requires us to have a custom scrollbar which is something we do not want to do
The bottom left is actually a browser feature and should be there. 
https://stackoverflow.com/questions/14817848/div-with-rounded-corners-and-internal-scrollbars

**Comment by maxrchung** [comment]
@agliga Thanks for the response Andrew. For what it's worth, I played around a bit in console and have a solution with some custom styling. Basically, it is moving the `border` styling to the wrapper element and also adding a `overflow: hidden` to the wrapper. Not very pretty and probably more of a hack but fixes it for me.

https://github.com/eBay/skin/assets/3955187/d70650d5-62f5-4381-869c-1c679fb08856

**Comment by agliga** [comment]
Thanks for your reponse. 

There are a couple of problems with this approach. If you notice textbox code is common across all the other textbox components not just textarea. 
If we move the border to the parent, we lose the ability to change the color of the border through aria-invalid (since the parent textbox container element has the border but the color is controlled by the child. We can't cascade up in CSS).
Another issue is this causes a problem on floating label and would requrie a rework and repositioning. 

So while it does seem simple, there are some usecases which are broken if we do change.
The best way would be to add a custom scrollbar. However, since this is an edge case and something that browsers should support we almost feel that it's not worth it just so support this edge case.
