### ISSUE TITLE
Menu: Add width for expand button without label

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#244]
On adding the `expand-btn--small` modifier, the width of the button should change to match it's height which is currently 32px.

**Before**
<img width="365" alt="screen shot 2018-06-28 at 4 59 07 pm" src="https://user-images.githubusercontent.com/5200733/42066293-998fa712-7af4-11e8-9c00-74977a128256.png">

**After**
<img width="79" alt="screen shot 2018-06-28 at 4 45 48 pm" src="https://user-images.githubusercontent.com/5200733/42066301-a6aab3e2-7af4-11e8-923b-fc3d19011191.png">

**Comment by ianmcburnie** [comment]
Hmm, this one is a little trickier than I first thought, because the left/right padding is always added by default to the button element, and we have no way of knowing if there is text or no text alongside the icon at that point. So I think we either:

1. Switch from using padding on root button to margin on child span (would affect all expand buttons)
1. Create a new block modifier, e.g. `expand-btn--no-text`

Anyhow, as it needs a bit more thought we will put it on backlog for now. Workaround on app side would be simply to set a width or max width for now.

**Comment by msendlakowski** [comment]
I'm going with option 2 above, and only for DS4 since DS6 no longer supports small buttons.
