### ISSUE TITLE
Actionable: Normalize between DS4 and DS6

### ISSUE THREAD

**Issue by seangates** [eBay/skin#440]
As the title suggests, we should normalize the duplicated style rules between the actionable module between DS4 and DS6.

Additionally, this includes adding Actionable to the DS6 documentation and normalizing the docs, too.

**Comment by ianmcburnie** [comment]
Actionable is also not "advertised" in the ds6 docs (left nav), so we can look into that too. I think it was left out because there was no concept of a borderless icon button in ds6 *at the time*.

<img width="158" alt="screen shot 2018-10-24 at 3 18 43 pm" src="https://user-images.githubusercontent.com/38065/47465113-4fe5ce80-d7a0-11e8-9171-2724d1c4b9e4.png">

**Comment by seangates** [comment]
Cool. I believe that could be part of this work, since we can essentially be normalizing docs, too. I'll change the title.

**Comment by ianmcburnie** [comment]
Done in 7.0.0 branch.
