### ISSUE TITLE
Textbox: icon layout issue in RTL languages

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#458]
Looks like incorrect margin or padding is set when textbox has an icon in right to left languages. Should be a simple fix.

LTR:

<img width="241" alt="screen shot 2018-11-16 at 3 16 52 pm" src="https://user-images.githubusercontent.com/38065/48652172-0198a980-e9b3-11e8-840e-45d1d79352c9.png">

RTL:

<img width="247" alt="screen shot 2018-11-16 at 3 16 40 pm" src="https://user-images.githubusercontent.com/38065/48652177-05c4c700-e9b3-11e8-854c-b9fad9029010.png">

**Comment by rachelvillamin** [comment]
Thanks Ian :) Can I pick this ticket up as well? Since it's a good first issue :P And it's related to the other issue I'm working on.

**Comment by rachelvillamin** [comment]
Hi Ian,

Is this the expected behaviour when dir attribute is set to "rtl" ?

<img width="997" alt="screen shot 2018-11-19 at 4 38 58 pm" src="https://user-images.githubusercontent.com/20077653/48688710-6fdfa500-ec1b-11e8-9597-c9dcd4eb0b1e.png">

If this is the case, I have fixed this in my local. Let me know if I can push it in a new branch and raise a PR for it for your review.  Fix for DS6 below (right hand side):

<img width="1022" alt="screen shot 2018-11-19 at 4 54 37 pm" src="https://user-images.githubusercontent.com/20077653/48688815-d795f000-ec1b-11e8-91b4-026ff792c146.png">


Thanks.

**Comment by ianmcburnie** [comment]
Hi @rachelvillamin When dir is set to rtl we expect the prefix icon to appear to the right of the text.

**Comment by rachelvillamin** [comment]
Hi @ianmcburnie,

What is the expected behaviour when dir="rtl" is specified in this?

![screen shot 2018-11-20 at 1 39 50 pm](https://user-images.githubusercontent.com/20077653/48748130-e33ff000-ecc9-11e8-9ca9-3e37a6710adf.png)

**Comment by rachelvillamin** [comment]
Hi @ianmcburnie, 

I have fixed the padding issue for the textbox with the prefix icon when dir="rtl":

![screen shot 2018-11-20 at 1 50 40 pm](https://user-images.githubusercontent.com/20077653/48748524-5138e700-eccb-11e8-9de4-a352147cd202.png)

However, I'm not able to push my changes:

![screen shot 2018-11-20 at 1 51 52 pm](https://user-images.githubusercontent.com/20077653/48748591-7af20e00-eccb-11e8-9877-04742f75b124.png)

**Comment by ianmcburnie** [comment]
Try pushing again now. Should work.

**Comment by ianmcburnie** [comment]
Fix goes out in 6.2.0. Thanks @rachelvillamin !
