### ISSUE TITLE
Combo: allow an flag to opt out of background icons to reduce payload

### ISSUE THREAD

**Issue by seangates** [eBay/skin#460]
As reported in #457, we have a large payload of all icons of which most will not get used. To address this immediately we should allow for an opt-out of the icons in order to decrease the bundle size. We would accomplish this with a Lasso flag, e.g. `icon-opt-out`.

The proposal is as follows:

```
{
    "dependencies": [
        "@ebay/skin/core",
        "@ebay/skin/dialog",
        "@ebay/skin/form",
        "@ebay/skin/iconfont",
        "@ebay/skin/spinner",
        {
            "if-not-flag": "icon-opt-out",
            "path": "@ebay/skin/icon"
        }
    ]
}
```

**Comment by seangates** [comment]
@senthilp @ianmcburnie @trg ☝️

**Comment by ianmcburnie** [comment]
Available in 6.2.0-0 for testing.

**Comment by ianmcburnie** [comment]
@trg let us know if you can verify this. I have concerns that components like the ebayui carousel are also going to bring in the full icon set due to it's current dependencies:

https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-carousel/browser.json

**Comment by senthilp** [comment]
@ianmcburnie This will be a problem. Is it not possible to directly use the SVG markup inside carousel? Tagging @DylanPiercey for suggestions.

**Comment by DylanPiercey** [comment]
@ianmcburnie so it looks like there are a few more things than just the carousel pulling in the items and I think the change discussed might be more involved:

1. ebay-select https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-select/template.marko#L16
2. ebay-pagination https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-pagination/template.marko#L24

These two would require changes in both skin and ebayui AFAICT to switch to inline svgs (although I see no reason not to do this).

The carousel does not actually need to reference `@ebay/skin/icon` however there is a larger problem. The `ebay-icon` component references it for the `background` icons (and this gets pulled in no matter what). We could perhaps make it so that the transformer only imported the `@ebay/skin/icon` entry point if it is being used as a background SVG though, curious on your thoughts.
