### ISSUE TITLE
Typography: add support for bold and secondary variants

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#57]
Let's make it easier for developers to opt into bold or secondary variants by adding more mixins and classes. For example:

LESS:

```less
.large-text-1-bold;
.large-text-1-secondary;
```

CSS:

```css
.large-text-1 .bold-text
.large-text-1 .secondary-text
```

Regular primary will always be the default, except for giant text which is always primary & bold.

[Type Ramp.pdf](https://github.com/eBay/skin/files/1732437/Type.Ramp.pdf)

**Comment by JeffNixonCreative** [comment]
Would it make sense to map the class names to the naming convention designers are using in order to streamline the workflow by creating a common language between designers and developers?
[https://dsl.ebay.com/ds6/typography]

For instance, the designers will be calling out type styles as:
Banner 1
Headline 1
Headline 2
...etc.

Also, I think having "bold" and "regular" as a style classes would help, since designers are more than likely going to break those rules of the baseline styles for text...IMO.

**Comment by ianmcburnie** [comment]
It's the first I've heard about banner 1, headline 1. I was told those had been abolished in favor of giant, large, small, etc.

I will add `bold-text` and `secondary-text` classes. Primary is default.

**Comment by JeffNixonCreative** [comment]
Can you let me know who told you that so I can confirm and correct it both in the Sketch Library as well as the living document?

**Comment by ianmcburnie** [comment]
James.
