### ISSUE TITLE
Pagination: disabled prev/next is still clickable

### ISSUE THREAD

**Issue by abiyasa** [eBay/skin#584]
On the pagination example, we disable the prev link with attribute `aria-disabled=true`. 
However, the user is still able to click the link (tested on chrome and safari).

```
<nav class="pagination" aria-labelledby="pagination-heading" role="navigation">
  <span aria-live="polite" role="status">
    <h2 class="clipped" id="pagination-heading">Results Pagination - Page 1</h2>
  </span>
  <a aria-disabled="true" aria-label="Previous Page" class="pagination__previous" href="http://www.ebay.com/sch/i.html?_nkw=guitars">
    <span></span>
  </a>
  <ol class="pagination__items">
    ...
  </ol>
  <a aria-label="Next Page" class="pagination__next" href="http://www.ebay.com/sch/i.html?_nkw=guitars&_pgn=2">
    <span></span>
  </a>
</nav>
```

If it's necessary to have prev link on the first page, I would suggest to remove the attribute href:

```
<a aria-disabled="true" aria-label="Previous Page" class="pagination__previous">
  <span></span>
</a>
```

I tested it and the arrow icon is still rendered properly.

The same problem also happens on pagination with buttons.

```
<button aria-disabled="true" aria-label="Previous Page" class="pagination__previous">
  <span></span>
</button>
```

we could replace `aria-disabled` with attribute `disabled`. This will prevent button to be clicked.

```
<button disabled aria-label="Previous Page" class="pagination__previous">
  <span></span>
</button>
```

**Comment by ianmcburnie** [comment]
This is probably going to sound odd, but this is by design. When creating the MIND pattern and reviewing the types of bugs we often get for pagination, and common user difficulties, we decided to go with an approach whereby all the buttons and links are always kept in the tab index.

One reason for this is that if keyboard focus is on a button or link and we set it to `disabled` or remove the `href`, then the keyboard focus can jump to somewhere unpredictable. It's different from browser to browser. To avoid this unpredictability, we decided that the simplest approach was to keep focus on the element, but mark it visually and programmatically disabled. Essentially becoming a no-op or refresh. We coined the term "partially disabled". The other place we see this is in the carousel pattern.

Most of the above relates to client side pagination. For server side pagination, with full page reloads, there is no issue with having these things disabled or href removed, but I think we kept it all the same for the sake of consistency.

I will update the Skin documentation so as to avoid this current confusion. We can also review the MIND pattern behaviour at any time, if we think it should be changed or can be improved. The patterns continue to evolve, and so we value your input!

https://ebay.gitbook.io/mindpatterns/navigation/pagination

**Comment by abiyasa** [comment]
Thanks Ian for clarifying this. It makes sense to keep the link focusable even though it's disabled for the sake of predictability or consistency. 

I read again the MIND pattern for [pagination keyboard focus](https://ebay.gitbook.io/mindpatterns/navigation/pagination#keyboard), it's clearly stated that all links (including the prev/next ones) should be keyboard focusable even when visually/partially disabled. 
I just wasn't aware the reason or problems behind this rule before so thanks again for explaining this 🙂

I will close this issue then.
