### ISSUE TITLE
Menu: IE truncates long items when multiple items are clicked

### ISSUE THREAD

**Issue by seangates** [eBay/skin#589]
To reproduce the behavior:

- Open the menu
- Click on a short string item
- Click on a long string item

Notice that the first long string item will be come truncated.

### Before click
![image (24)](https://user-images.githubusercontent.com/105656/54454186-82c43b00-471e-11e9-9707-46015b2762ca.png)

### After click
![image (23)](https://user-images.githubusercontent.com/105656/54454146-704a0180-471e-11e9-830d-4d429a917540.png)

**Comment by ianmcburnie** [comment]
@seangates Would be great if you get a chance to look at this one too. Hopefully something simple.

**Comment by agliga** [comment]
So issue with this is flexbox isn't supported fully by IE11 and we are using flexbox for this container
The solution which works (tested in IE11) is to change `flex: 1` on each menu item to be `flex: 1 0 auto`. This is because of the IE11 default is not proper. 
For Firefox this will then break and we'll need to add a firefox override to be `flex: 1`
See: https://stackoverflow.com/questions/21600345/flexbox-and-internet-explorer-11-displayflex-in-html

**Comment by ianmcburnie** [comment]
Cool. A fix could go into 7.4.2 then.
