### ISSUE TITLE
Create a namespaced version for global header

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#696]
The eBay global header needs a tailored, optimised version of skin. In order to avoid cascade issues, all of its class selectors need to be namespaced. For example, `gh-button`, `gh-button--primary, gh-button__cell`.

**Comment by agliga** [comment]
We would simply create a new bundle and do something like: 
```
.gh {
  @import (less) url("skin.css");
}
```
Or something like that

**Comment by seangates** [comment]
No ... they need every class name to be fully scoped. See @ianmcburnie's comment above.

**Comment by ianmcburnie** [comment]
Can PostCSS not help here? Or a plugin?

https://postcss.org

**Comment by agliga** [comment]
It can, however the issue we are running into will be having to support ebayui. If we change combobox__items to be gh-combobox__items then ebayui will need to support that change as well. Otherwise all items will be broken.
Our initial discussion was to nest all properties and not use BEM (or use it but to nest properties inside a global selector)
IE 
```
.combobox {
   .combobox__items {}
   .combobox__combobox {}
}
```
This way we only have to change the root class in EbayUI to support the changes

**Comment by ianmcburnie** [comment]
Changing only the root class does not guarantee that a style will not be overridden. In our CSS not every selector begins with the root class. We should try and proceed with the option that is simplest for skin, if we can. Then figure out how to make ebayui work with that.

**Comment by ianmcburnie** [comment]
I might have to take that comment back.. now I see and understand what you are doing.

I was comparing it to this:

https://github.com/eBay/skin/blob/master/src/less/gh/ds6/gh-mixins.less

Which does (I think) have the problems I mention.
