### ISSUE TITLE
Checkbox: unchecked checkbox shows with blue border instead of grey in DS4

### ISSUE THREAD

**Issue by shawnsz** [eBay/skin#737]
Skin version: 7.4.7
The DS4 unchecked checkbox shows with blue border instead of grey.
In our app:
<img width="569" alt="Screen Shot 2019-08-03 at 12 17 52 AM" src="https://user-images.githubusercontent.com/10065231/62427916-55c1f600-b6c8-11e9-898e-f6da3b456b2d.png">
In Skin doc:
![Screen Shot 2019-08-04 at 2 59 14 PM](https://user-images.githubusercontent.com/10065231/62427939-9f124580-b6c8-11e9-936f-ef646cc14f1f.png)

**Comment by ianmcburnie** [comment]
Just a heads up @seangates that due to tight timelines, DS6.5 sprint tasks take priority over DS4 and DS6 bug fixes. I guess just use best judgment if something is a critical bug or not, but In this instance I would say teams should be able to live with a blue border a little while longer, until we get to them in our DS6.5 sprint (sprint 3 or 4 I think), or override themselves in the meantime. I would MUCH rather have all the sprint tasks taken care of first and a release to QA, before doing anything else.
