### ISSUE TITLE
Listbox Button: dropdown icon not visible when button is disabled

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#923]
# Bug Report

## Description
unable to see the arrow icon- It looks more like a disabled button
![image](https://user-images.githubusercontent.com/13157115/60615221-7de5ce80-9d83-11e9-8793-d4149a322670.png)

**Comment by ianmcburnie** [comment]
After further investigation, the state of expand button is a bit of a confusing mess. This is partly due to some of the visual differences and build-up of edge cases we've had to maintain between ds4 and ds6, but I think we can clean things up and normalize more. DS4 needs to be brought much closer in line with ds6 to make this code easier to reason with going forward. I'm going to have a go at this as part of v10.

**Comment by ianmcburnie** [comment]
Fixed in 10.0.0
